// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6CSch3ysOYTvLa5qgovGCBBFHHZiggw',
    appId: '1:1097831759315:web:c723be5fe57dee8bd78326',
    messagingSenderId: '1097831759315',
    projectId: 'firebase-calculator1',
    authDomain: 'fir-calculator1.firebaseapp.com',
    storageBucket: 'firebase-calculator1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADU-712SdAinUtCunAVvo9bpKLjpFrnH0',
    appId: '1:1097831759315:android:2efb64e4e78a5694d78326',
    messagingSenderId: '1097831759315',
    projectId: 'firebase-calculator1',
    storageBucket: 'firebase-calculator1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5gX2EdzpLciXVKd3z-p1YcBZwsCOj8jc',
    appId: '1:1097831759315:ios:b14b48f829237c0cd78326',
    messagingSenderId: '1097831759315',
    projectId: 'firebase-calculator1',
    storageBucket: 'firebase-calculator1.firebasestorage.app',
    iosBundleId: 'com.example.calculatorFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5gX2EdzpLciXVKd3z-p1YcBZwsCOj8jc',
    appId: '1:1097831759315:ios:b14b48f829237c0cd78326',
    messagingSenderId: '1097831759315',
    projectId: 'firebase-calculator1',
    storageBucket: 'firebase-calculator1.firebasestorage.app',
    iosBundleId: 'com.example.calculatorFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo6CSch3ysOYTvLa5qgovGCBBFHHZiggw',
    appId: '1:1097831759315:web:3c018b92dbcce8a2d78326',
    messagingSenderId: '1097831759315',
    projectId: 'firebase-calculator1',
    authDomain: 'fir-calculator1.firebaseapp.com',
    storageBucket: 'firebase-calculator1.firebasestorage.app',
  );
}
